
services:
  db:
    image: mysql:8.0
    container_name: database
    restart: always
    environment:
     - MYSQL_ROOT_PASSWORD=1234
     - MYSQL_DATABASE=rafaydb
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app
  app:
    build: .
    container_name: book-api
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
     - DB_URL=jdbc:mysql://database:3306/rafaydb
     - DB_USERNAME=root
     - DB_PASSWORD=1234
    networks:
      - app
    command: ["java","-jar","app.jar"]

networks:
  app:
    driver: bridge

volumes:
  db_data:

